# Generated by Django 5.1.4 on 2024-12-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_rename_tag_tags_posts_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
